baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Jerry,Fu Zhang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: More about me
          url: about/
          weight: 1 
        # - name: Publications
        #   url: publications/
        #   weight: 2
        - name: Projects
          url: project/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4

params:
    description: "This is me"
    author: Jerry Fu Zhang
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: false
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","publication","project","tags"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: true
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: 张辅
          subtitle: "A researcher determined to maximise the potential of computers for healthcare and medical applications  "
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:

            - name: More about me
              url: about/
            # - name: Publications
            #   url: Publications/
            - name: Projects
              url: project/ 
            - name: Tags
              url: tags/



    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:jerry-fu.zhang@polyu.edu.hk
        - name: LinkedIn
          url: https://www.linkedin.com/in/fuzhang049/
        - name: Location
          url: https://www.polyu.edu.hk/comp/people/research-staff-and-students/
        # - name: Google Scholar
        #   url: 
        - name: GitHub
          url: https://github.com/nablafx
 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jerry,Fu Zhang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2